# Generated by Django 4.2.2 on 2023-07-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_contestmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
