# Generated by Django 4.2.2 on 2023-07-11 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(choices=[('school', 'Школа'), ('kindergarten', 'Детский сад'), ('other', 'Другое')], max_length=15)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='participantmodel',
            name='kindergarten',
        ),
        migrations.RemoveField(
            model_name='participantmodel',
            name='other',
        ),
        migrations.RemoveField(
            model_name='participantmodel',
            name='school',
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='organization_type',
            field=models.CharField(choices=[('school', 'Школа'), ('kindergarten', 'Детский сад'), ('other', 'Другое')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='KindergartenModel',
        ),
        migrations.DeleteModel(
            name='SchoolModel',
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='users.organization'),
            preserve_default=False,
        ),
    ]
