# Generated by Django 4.2.2 on 2023-07-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resultmodel',
            table='surv_results',
        ),
        migrations.AlterModelTable(
            name='surveymodel',
            table='surv_surveys',
        ),
    ]
