# Generated by Django 4.2.2 on 2023-07-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_surveymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.surveymodel'),
        ),
    ]
